# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Run linter
      run: bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    name: test (ruby ${{ matrix.ruby }} / rails ${{ matrix.rails_version }} ${{ matrix.additional_name }})
    strategy:
      matrix:
        ruby: [2.7, '3.0']
        rails_version: ['~> 6.1', '~> 7.0']
        bootstrap_version: [null]
        api: [null]
        additional_engine_cart_rails_options: ['']
        additional_name: ['']
        include:
        - ruby: '3.1'
          rails_version: '~> 7.0'
        - ruby: '3.0'
          rails_version: '~> 7.0'
          bootstrap_version: '~> 4.0'
          additional_name: '/ Bootstrap 4'
        - ruby: '2.6'
          rails_version: '~> 6.0.3'
        - ruby: '3.0'
          rails_version: '~> 7.0'
          api: 'true'
          additional_engine_cart_rails_options: --api
          additional_name: '/ API'
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      BOOTSTRAP_VERSION: ${{ matrix.bootstrap_version }}
      BLACKLIGHT_API_TEST: ${{ matrix.api }}
      ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-test ${{ matrix.engine_cart_rails_options }}"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker-compose build app
